### ISSUE TITLE
improve get_weather_info function

### ISSUE THREAD

**Issue by taka-rl** [taka-rl/python_practice#1]
Targeted code: projects/chat_bot/main.py
Targeted function get_weather_info()

To get the weather information, I use OpenWeather API.
However, currently I can't obtain the weather information of the location that I want.  
And It returns the same value.   
I assume that I need to modify url to access. But I'm not sure how I should change it....  
The current url setting: url = f'http://api.openweathermap.org/data/2.5/weather?id=524901&appid={api_key}&units=metric'
following OpenWeather web page: https://openweathermap.org/faq#error401%20for%20more%20info

How can I use an API key in API calls?
To authorise a request from you and process it, we require you to use your unique API key in each API call.
In order to do this, add your API key as an appid parameter to the GET request, like in the following example:
api.openweathermap.org/data/2.5/weather?id=524901&appid=YOUR_API_KEY
Just use your API key instead of “YOUR_API_KEY” with your personal API key, it can be found in your personal account on the [“API keys” page](https://home.openweathermap.org/api_keys). You can also create additional API keys there.

**Comment by asksmruti** [comment]
In this URL, you are requesting for a specific location's weather information. 
In your bot application, you need to ask for location detail, which can be parsed as parameter.
It could be city/country or geographical location or city id. The city ID can be obtained from here - 

https://bulk.openweathermap.org/sample/city.list.json.gz 

In this case, the city id is 524901 which is _Moscow_ code. Hence you would be always getting Moscow's weather info.

**Comment by taka-rl** [comment]
Hi, asksmruti!

Thank you very much for your detailed information and json file!!

I have researched about OpenWeather API and I found parameters information to get information by using the location. 
https://openweathermap.org/current#builtin
Considering ways including your advice, in the end I decided to change url structure like this.
url = f'http://api.openweathermap.org/data/2.5/weather?q={location}&appid={api_key}&units=metric' 

Again, thank you for your time and support!!
